// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7LIwzuuYww8gSPzGuRdoay9frWP7X8WE',
    appId: '1:228351780401:web:09994ad7db59c3fe7bd710',
    messagingSenderId: '228351780401',
    projectId: 'softkormo-8ea9c',
    authDomain: 'softkormo-8ea9c.firebaseapp.com',
    storageBucket: 'softkormo-8ea9c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOoJGhK6UuWjCO26ODXFNTwGlt_lmhiuI',
    appId: '1:228351780401:android:faeb7ba8e3bf09317bd710',
    messagingSenderId: '228351780401',
    projectId: 'softkormo-8ea9c',
    storageBucket: 'softkormo-8ea9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9xVzL4G6Tk1f3bbFne7IFIFiz7QhN0CI',
    appId: '1:228351780401:ios:ee3ac23c4d348be17bd710',
    messagingSenderId: '228351780401',
    projectId: 'softkormo-8ea9c',
    storageBucket: 'softkormo-8ea9c.firebasestorage.app',
    iosBundleId: 'com.example.softkormo',
  );
}
